" Runtime Paths "
set rtp+=/usr/local/opt/fzf "path for fzf

" Filetype "
set nocompatible
filetype off
filetype plugin indent on

" File Explorer "
let g:netrw_list_hide= '.*\.swp$,\.orig$'

" Syntax "
syntax on
let g:python_highlight_all = 1

" Characters "
set backspace=indent,eol,start

" Spacing "
set autoindent
set expandtab
set shiftwidth=2
set tabstop=2

" Mouse "
set mouse=a

" Visual "
set background=dark
set number
set ruler
set nowrap
set laststatus=2
set noshowmode

" Gruvbox Colors "
let g:gruvbox_inverse = 0

" Randomize Colorscheme "
let colorschemes = ['everforest', 'gruvbit', 'gruvbox', 'gruvbox-material', 'monokai', 'monokai_pro', 'sonokai']
execute 'colorscheme' colorschemes[rand() % (len(colorschemes) - 1 ) ]

" Generic Colors "
highlight RipgrepBlue cterm=none ctermfg=14   ctermbg=none
highlight DiffAdd     cterm=none ctermfg=118  ctermbg=none
highlight DiffDelete  cterm=none ctermfg=52   ctermbg=52
highlight DiffChange  cterm=none ctermfg=none ctermbg=none
highlight DiffText    cterm=none ctermfg=220  ctermbg=240
highlight Search      cterm=none ctermfg=14   ctermbg=none

" Persist After ColorScheme Change
autocmd ColorScheme * highlight RipgrepBlue cterm=none ctermfg=14   ctermbg=none
autocmd ColorScheme * highlight DiffAdd     cterm=none ctermfg=118  ctermbg=none
autocmd ColorScheme * highlight DiffDelete  cterm=none ctermfg=52   ctermbg=52
autocmd ColorScheme * highlight DiffChange  cterm=none ctermfg=none ctermbg=none
autocmd ColorScheme * highlight DiffText    cterm=none ctermfg=220  ctermbg=240
autocmd ColorScheme * highlight Search      cterm=none ctermfg=14   ctermbg=none

" Functions "
function! Diff_Toggle()
    if &diff
        diffoff
    else
        diffthis
    endif
:endfunction

" Commands "
command! -bang -nargs=0 DiffToggle call Diff_Toggle()
command! -bang -nargs=* -complete=dir Fzf call fzf#vim#files(<q-args>, <bang>0)
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4.. --color hl:14,hl+:214'}, <bang>0)
command! -bang -nargs=0 LspRestart call lsp#disable() | call lsp#enable()

" Mappings "
" Enter on pop up menu selects
inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"
" Set highlight on search
nnoremap <silent> <leader>/ :set hlsearch!<CR>
" Search for word under cursor in file
nnoremap <silent> <leader>f /<C-r><C-w><CR>N :set hlsearch<CR>

" Plugins "
" Lightline "
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
let g:lightline.component_expand = {
      \  'gitdiff': 'lightline#gitdiff#get',
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_infos': 'lightline#ale#infos',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
let g:lightline.component_function = {
      \  'gitbranch': 'FugitiveHead' }
let g:lightline.component_type = {
      \  'linter_checking': 'right',
      \  'linter_infos': 'right',
      \  'linter_warnings': 'warning',
      \  'linter_errors': 'error',
      \  'linter_ok': 'right',
      \ }
let g:lightline.active = {
      \ 'left': [ [ 'mode', 'paste' ],
      \           [ 'gitbranch' ],
      \           [ 'gitdiff', 'filename', 'readonly', 'modified' ] ],
      \ 'right': [ [ 'linter_errors', 'linter_warnings', 'linter_ok' ],
      \            [ 'lineinfo' ],
      \            [ 'percent' ] ] }
let g:lightline#ale#indicator_warnings = "\u23f5"
let g:lightline#ale#indicator_errors = "\u2716"
let g:lightline#ale#indicator_ok = "\u2713"
let g:lightline#gitdiff#indicator_added = "+"
let g:lightline#gitdiff#indicator_deleted = "-"
let g:lightline#gitdiff#indicator_modified = "\u26cf"

" Ripgrep "
" Mappings
" RG cursor
nnoremap <silent> <C-f> :Rg <C-r><C-w><CR>

" FZF "
" Settings "
let g:fzf_colors =
      \ { 'hl': ['fg', 'RipgrepBlue'],
      \  'bg+': ['bg', 'PMenu'],
      \  'hl+': ['fg', 'CursorLineNr'] }

" Quickfix Reflector "
" Settings
let g:qf_modifiable = 0

" Fugitive "
" Mappings
" List all diffed files in quickfix list from provided branch/commit
cmap difflist Git difftool --name-only
" Open all diff files in split view from provided branch/commit (use for code review)
cmap PR Git difftool -y
" Opens all conflicted files in a 3 pane split
cmap Merge Git mergetool -y
" pull local (left) changes into merge file
cmap DGL diffget //2**/<C-r>%
" pull remote (right) changes into merge file
cmap DGR diffget //3**/<C-r>%
" Toggle diff between files in current tab
nnoremap <silent> <leader>t :call Diff_Toggle()<CR>

" Vim-lsp "
" TODO figure out how to only lint on save
" Settings
let g:asyncomplete_auto_popup = 0
let g:lsp_signature_help_enabled = 0
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_echo_delay = 0
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_float_delay = 100
let g:lsp_diagnostics_signs_delay = 0
let g:lsp_diagnostics_signs_error = {'text': '>>'}
let g:lsp_diagnostics_signs_warning = {'text': '--'}
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_document_code_action_signs_delay = 0
" Mappings
nnoremap <silent> <C-p> :LspDefinition<CR>
nnoremap <silent> <leader>d :LspPeekDefinition<CR>
nnoremap <silent> <C-k> :LspImplementation<CR>
nnoremap <silent> <leader>i :LspPeekImplementation<CR>
nnoremap <silent> <C-@> :LspReferences<CR>
nnoremap <silent> <C-n> :LspRename<CR>
nnoremap <silent> <leader>h :LspHover<CR>
nnoremap <silent> ® :LspRestart<CR>
imap <c-@> <plug>(asyncomplete_force_refresh)
cmap LspReplace LspRename

" ALE "
" Settings
let g:ale_lint_delay = 0
let g:ale_lint_diff = 1
let g:ale_lint_on_enter = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linters = {
      \  'cpp': [
      \    'clang',
      \    'clangcheck',
      \    'clangd',
      \    'flawfinder',
      \  ],
      \  'elixir': [
      \    'credo',
      \    'elixir-ls',
      \  ],
      \  'go': [
      \    'golint',
      \    'gopls',
      \  ],
      \  'javascript': [
      \    'eslint',
      \    'flow-language-server',
      \  ],
      \  'typescript': [
      \    'prettier',
      \    'eslint',
      \  ],
      \  'python': [
      \    'pyright',
      \  ],
      \  'rust': [
      \    'rustc',
      \    'rls',
      \  ],
      \  'vim': [
      \    'vimls',
      \  ],
      \ }
let g:ale_fixers = {
      \  'cpp': [
      \    'clang-format',
      \    'clangtidy',
      \  ],
      \  'elixir': [
      \    'mix_format',
      \  ],
      \  'go': [
      \    'gofmt',
      \    'goimports',
      \  ],
      \  'javascript': [
      \    'prettier',
      \    'eslint',
      \  ],
      \  'typescript': [
      \    'prettier',
      \    'eslint',
      \  ],
      \  'rust': [
      \    'rustfmt',
      \  ],
      \ }
let g:ale_fix_on_save = 1
let g:ale_detail_to_floating_preview=1
let g:ale_elixir_elixir_ls_release = $WORKSPACE.'/elixir-ls/release'
let g:ale_virtualtext_cursor = 'disable'
let g:ale_echo_msg_format = '%s'
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_sign_info = ' ?'
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'


" Mappings
nnoremap <silent> <C-a> :ALEToggle<CR>
nnoremap <silent> <C-e> :ALEDetail<CR>
inoremap <silent> <C-a> <C-\><C-O>:ALEToggle<CR>

" GitGutter "
" Mappings
nnoremap <silent> <C-s> :GitGutterToggle<CR>
inoremap <silent> <C-s> <C-\><C-O>:GitGutterToggle<CR>
