" Runtime Paths "
set rtp+=/usr/local/opt/fzf "path for fzf

" Filetype "
set nocompatible
filetype off
filetype plugin indent on

" File Explorer "
let g:netrw_list_hide= '.*\.swp$,\.orig$'

" Syntax "
syntax on
let g:python_highlight_all = 1

" Characters "
set backspace=indent,eol,start

" Spacing "
set autoindent
set expandtab
set shiftwidth=2
set tabstop=2

" Mouse "
set mouse=a

" Visual "
set background=dark
set laststatus=2
set noequalalways
set noshowmode
set nowrap
set number
set ruler

" Gruvbox Colors "
let g:gruvbox_inverse = 0

" Randomize Colorscheme "
let colorschemes = ['everforest', 'gruvbit', 'gruvbox', 'gruvbox-material', 'monokai', 'monokai_pro', 'sonokai']
execute 'colorscheme' colorschemes[rand() % (len(colorschemes) - 1 ) ]
let $BAT_THEME = g:colors_name

" Generic Colors "
highlight RipgrepBlue cterm=none ctermfg=14   ctermbg=none
highlight DiffAdd     cterm=none ctermfg=118  ctermbg=none
highlight DiffDelete  cterm=none ctermfg=52   ctermbg=52
highlight DiffChange  cterm=none ctermfg=none ctermbg=none
highlight DiffText    cterm=none ctermfg=220  ctermbg=240
highlight Search      cterm=none ctermfg=14   ctermbg=none

" Persist After ColorScheme Change
autocmd ColorScheme * highlight RipgrepBlue cterm=none ctermfg=14   ctermbg=none
autocmd ColorScheme * highlight DiffAdd     cterm=none ctermfg=118  ctermbg=none
autocmd ColorScheme * highlight DiffDelete  cterm=none ctermfg=52   ctermbg=52
autocmd ColorScheme * highlight DiffChange  cterm=none ctermfg=none ctermbg=none
autocmd ColorScheme * highlight DiffText    cterm=none ctermfg=220  ctermbg=240
autocmd ColorScheme * highlight Search      cterm=none ctermfg=14   ctermbg=none

" Plugin Settings "
" ALE
" TODO figure out how to only lint on save
let g:ale_detail_to_floating_preview=1
let g:ale_echo_msg_format = '%s'
let g:ale_elixir_elixir_ls_release = $WORKSPACE.'/elixir-ls/release'
let g:ale_fix_on_save = 1
let g:ale_lint_delay = 0
let g:ale_lint_diff = 1
let g:ale_lint_on_enter = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_sign_error = '>>'
let g:ale_sign_info = ' ?'
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_virtualtext_cursor = 'disable'
let g:ale_linters = {
      \  'cpp': [
      \    'clang',
      \    'clangcheck',
      \    'clangd',
      \    'flawfinder',
      \  ],
      \  'elixir': [
      \    'credo',
      \    'elixir-ls',
      \  ],
      \  'go': [
      \    'golint',
      \    'gopls',
      \  ],
      \  'javascript': [
      \    'eslint',
      \    'flow-language-server',
      \  ],
      \  'typescript': [
      \    'prettier',
      \    'eslint',
      \  ],
      \  'python': [
      \    'pyright',
      \  ],
      \  'rust': [
      \    'rustc',
      \    'rls',
      \  ],
      \  'vim': [
      \    'vimls',
      \  ],
      \ }
let g:ale_fixers = {
      \  'cpp': [
      \    'clang-format',
      \    'clangtidy',
      \  ],
      \  'elixir': [
      \    'mix_format',
      \  ],
      \  'go': [
      \    'gofmt',
      \    'goimports',
      \  ],
      \  'javascript': [
      \    'prettier',
      \    'eslint',
      \  ],
      \  'typescript': [
      \    'prettier',
      \    'eslint',
      \  ],
      \  'rust': [
      \    'rustfmt',
      \  ],
      \ }

" Fugitive
" Autoupdate git window
autocmd BufWritePost,BufDelete * if bufexists('fugitive://') | execute 'Git' | endif

" Fzf/Ripgrep
let g:fzf_vim = {}
let g:fzf_vim.files_options = '--color hl:14,hl+:214'
let g:fzf_vim.rg_options = '--delimiter : --nth 4.. --color hl:14,hl+:214'

" Lightline "
let g:lightline = {
      \  'colorscheme': 'wombat',
      \ }
let g:lightline.component_expand = {
      \  'gitdiff': 'lightline#gitdiff#get',
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_infos': 'lightline#ale#infos',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
let g:lightline.component_function = {
      \  'gitbranch': 'FugitiveHead' }
let g:lightline.component_type = {
      \  'linter_checking': 'right',
      \  'linter_infos': 'right',
      \  'linter_warnings': 'warning',
      \  'linter_errors': 'error',
      \  'linter_ok': 'right',
      \ }
let g:lightline.active = {
      \ 'left': [ [ 'mode', 'paste' ],
      \           [ 'gitbranch' ],
      \           [ 'gitdiff', 'filename', 'readonly', 'modified' ] ],
      \ 'right': [ [ 'linter_errors', 'linter_warnings', 'linter_ok' ],
      \            [ 'lineinfo' ],
      \            [ 'percent' ] ] }
let g:lightline#ale#indicator_errors = "\u2716"
let g:lightline#ale#indicator_ok = "\u2713"
let g:lightline#ale#indicator_warnings = "\u23f5"
let g:lightline#gitdiff#indicator_added = "+"
let g:lightline#gitdiff#indicator_deleted = "-"
let g:lightline#gitdiff#indicator_modified = "\u26cf"

" Lsp (vim-lsp)
" TODO figure out how to only lint on save
autocmd User lsp_float_opened
      \ call popup_setoptions(lsp#ui#vim#output#getpreviewwinid(), {
      \  'borderchars': ['─','│','─','│','┌','┐','┘','└'],
      \ })
let g:asyncomplete_auto_popup = 0
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_echo_delay = 0
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_float_delay = 100
let g:lsp_diagnostics_signs_delay = 0
let g:lsp_diagnostics_signs_error = {'text': '>>'}
let g:lsp_diagnostics_signs_warning = {'text': '--'}
let g:lsp_document_code_action_signs_delay = 0
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_signature_help_enabled = 0

" Quickfix Reflector 
let g:qf_modifiable = 0

" Functions "
function! Close_Diff()
  if (!&diff && !getbufvar('#', '&diff')) || (bufname('%') !~ '^fugitive:' && bufname('#') !~ '^fugitive:')
    echom "Not in diff view."
    return
  endif

  " Close current buffer if alternate is not fugitive but current one is.
  if bufname('%') =~ '^fugitive:' && bufname('#') !~ '^fugitive:' 
    if bufwinnr("#") == -1
      b #
      bd #
    else
      bd
    endif
  else
    bd #
  endif
endfunction

function! Diff_Toggle()
    if &diff
        call Close_Diff()
    else
        Gdiff
        wincmd p
    endif
endfunction

function! Git_Toggle() abort
  for l:winnr in range(1, winnr('$'))
    if !empty(getwinvar(l:winnr, 'fugitive_status'))
      exe l:winnr 'close'
      return
    endif
  endfor
  belowright keepalt Git
  resize 10
  setlocal winfixheight
endfunction

" Commands "
command! -bang -nargs=0 DiffToggle call Diff_Toggle()
command! -bang -nargs=0 GitToggle call Git_Toggle()
command! -bang -nargs=0 LspRestart call lsp#disable() | call lsp#enable()
command! HelpTags packloadall | silent! helptags ALL

" Mappings "

" Originally mapped to group similar functionality (ie all LSP functions
" interact with CTRL), but have now changed so the mappings group similar
" interaction patterns (ie does it open new buffers? floating window? etc)

" General Pattern
" ]/[ mappings navigate in search
" <leader> mappings do in buffer operations
" <Space> mappings open new buffers/fullscreen floating windows
" <C-*> (ctrl) mappings jump buffers, do under cursor operations,
" and replace <leader>/<Space> in insert mode operations

" Quit tab
cnoreabbrev <expr> qt (getcmdtype() == ':' ? 'tabclose' : 'qt')
" Open all diff files in split view from provided branch/commit (use for code review)
cnoreabbrev <expr> PR (getcmdtype() == ':' && getcmdline() ==# 'PR' ? 'Git difftool -y' : 'PR')
" Lists all changed files in quickfix list
cnoreabbrev <expr> difflist (getcmdtype() == ':' && getcmdline() ==# 'difflist' ? 'Git difftool --name-only' : 'difflist')
" Opens all conflicted files in a 3 pane split
cnoreabbrev <expr> Merge (getcmdtype() == ':' && getcmdline() ==# 'Merge' ? 'Git mergetool -y' : 'Merge')
" Pull local (left) changes into merge file
cnoreabbrev <expr> DGL (getcmdtype() == ':' && getcmdline() ==# 'DGL' ? 'diffget //2**/<C-r>%' : 'DGL')
" Pull remote (right) changes into merge file
cnoreabbrev <expr> DGR (getcmdtype() == ':' && getcmdline() ==# 'DGR' ? 'diffget //3**/<C-r>%' : 'DGR')
" Map common mistype for symbol renaming
cnoreabbrev <expr> LspReplace (getcmdtype() == ':' && getcmdline() ==# 'LspReplace' ? 'LspRename' : 'LspReplace')

" Enter - select from popup menu
inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"

" / - Highlight
" Set highlight on buffer search
nnoremap <silent> <leader>/ :set hlsearch!<CR>

" A - Alerts
" Toggle gutter diagnostics
nnoremap <silent> <leader>d :ALEToggle<CR>
inoremap <silent> <C-d> <C-\><C-O>:ALEToggle<CR>

" C - Close
" Closes quickfix window (note not safe to remap for ctrl-C)
nnoremap <silent> <Space>c :ccl<CR>

" D - Diff/Definition
" Pop up definition
nnoremap <silent> <leader>d :LspPeekDefinition<CR>
" Open diff buffer
nnoremap <silent> <Space>d :DiffToggle<CR>
" Jump to definition
nnoremap <silent> <C-d> :LspDefinition<CR>

" E - Error
" Jump to next error/warning
nnoremap <silent>]e :ALENextWrap<CR>
" Jump to previous error/warning
nnoremap <silent>[e :ALEPreviousWrap<CR>
" Pop up full error
nnoremap <silent> <leader>e :ALEDetail<CR>
" Open quickfix with diagnostics (errors) listed
nnoremap <silent> <Space>e :ALEPopulateQuickfix<CR>:copen<CR>

" F - Find
" Search for word under cursor in file
nnoremap <silent> <leader>f /<C-r><C-w><CR>N :set hlsearch<CR>
" Open ripgrep search
nnoremap <silent> <Space>f :Rg<CR>
" Ripgrep word under cursor
nnoremap <silent> <C-f> :Rg <C-r><C-w><CR>

" G - Git
" Toggle gutter diff
nnoremap <silent> <leader>g :GitGutterToggle<CR>
inoremap <silent> <C-g> <C-\><C-O>:GitGutterToggle<CR>
" Open fugitive git status window
nnoremap <silent> <Space>g :GitToggle<CR>

" H - Hover details
" Pop up LSP hover information
nnoremap <silent> <leader>h :LspHover<CR>

" I - Implementation
" Pop up implementation
nnoremap <silent> <leader>i :LspPeekImplementation<CR>
" Jump to implementation
nnoremap <silent> <Space>i :LspImplementation<CR>
nnoremap <silent> <C-i> :LspImplementation<CR>

" N - Next/Name
" Next item in quickfix list
nnoremap <silent>]n :cn<CR>
" Previous item in quickfix list
nnoremap <silent>[n :cp<CR>
" Symbol (re)name (lsp identified occurences)
nnoremap <silent> <leader>n /<C-r><C-w><CR>N :LspRename<CR>
nnoremap <silent> <C-n> :LspRename<CR>

" P - Project
" Open file search
nnoremap <silent> <Space>p :Files<CR>

" R - References/Restart
" Restart the LSP server
nnoremap <silent> <leader>r :LspRestart<CR>
" Open references
nnoremap <silent> <Space>r :LspReferences<CR>
nnoremap <silent> <C-r> :LspReferences<CR>

" U - Update/Undo
" Reload (update) buffer with any changes
nnoremap <silent> <leader>u :e<CR>
nnoremap <silent> <Space>u :e<CR>
" FORCE reload (update) buffer with any changes
nnoremap <silent> <C-u> :e!<CR>
" Redo mapping basic capital U to redo since ctrl-r is remapped
nnoremap <silent> U :redo<CR>

" W - Window
nnoremap <leader>w :execute "resize " . input("Height: ")<CR>

" Arrow Keys - Buffer Sizes
nnoremap <leader><UP> :resize +5<CR>
nnoremap <leader><DOWN> :resize -5<CR>
nnoremap <leader><LEFT> :vertical resize -5<CR>
nnoremap <leader><RIGHT> :vertical resize +5<CR>

" Space - Completion (ie 'blank')
" Trigger autocompletion
imap <c-@> <plug>(asyncomplete_force_refresh)
